### ISSUE TITLE
[PROGRESS] Todo List 🔔 

### ISSUE THREAD

**Issue by realyukii** [hansputera/bilibili-dl#6]
## Logic Business
Empty

## Fix and Refactor
- [x] infinite scroll [issue 1](https://github.com/vercel/swr/discussions/2652), [issue 2](https://github.com/vercel/swr/discussions/2709) and other related [links](https://github.com/vercel/swr/issues/176) | ✅ [[5cd257d](https://github.com/Reyuki-san/bilibili-dl/commit/5cd257de01ca19427ad5540f80ddfea9d0ac958c)]

## UI UX
- [ ] implement skeleton as fallback
- [x] make anime timeline list more interactive with day picker | ✅ [bb39f82](https://github.com/Reyuki-san/bilibili-dl/commit/bb39f82279292fb9b19865d55ee5522d6263aa44)
- [ ] mantine carousel [issues](https://github.com/mantinedev/mantine/discussions/4350)
